version: "3"

tasks:
  default:
    cmds:
      - task: debug

  run-react-dev-tools:
    internal: true
    cmds:
      - pnpm react-devtools

  run-tauri-dev:
    aliases:
      - td
    interactive: true
    preconditions:
      - sh: pnpm i
    cmds:
      - pnpm tauri dev

  debug:
    aliases:
      - d
    deps:
      - run-tauri-dev
    cmds:
      - echo "debug seeion started 💥"

  debug-w-react-devtools:
    aliases:
      - dw
    deps:
      - run-tauri-dev
      - run-react-dev-tools
    cmds:
      - echo "debug seeion ended 💥"
